{% set version = "2.1.0" %}
{% set sha256 = "079fd1ab888ab2aa6b6ea06edb152706fce0ef0036f5a94c0a3cc5f06afb0f01" %}

package:
    name: pythreejs
    version: {{ version }}

source:
    fn: pythreejs-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pythreejs/pythreejs-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - pip
        - python
        - setuptools
        - nodejs
    run:
        - python
        - ipywidgets >=7,<8
        - numpy
        - traittypes
        - ipydatawidgets

test:
    imports:
        - pythreejs

about:
    home: https://github.com/jupyter-widgets/pythreejs
    license: BSD 3-Clause
    summary: A Python / ThreeJS bridge utilizing the Jupyter widget infrastructure.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - vidartf
