{% set version = "0.2.1" %}

package:
    name: pythreejs
    version: {{ version }}

source:
    fn: pythreejs-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pythreejs/pythreejs-{{ version }}.tar.gz
    sha1: 0fd62ce51c72697bf5c16e212b7474518977365a

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - jupyter
    run:
        - python
        - ipywidgets >=5.1.5

test:
    imports:
        - pythreejs

about:
    home: https://github.com/jovyan/pythreejs
    license: BSD 3-Clause
    summary: A Python / ThreeJS bridge utilizing the Jupyter widget infrastructure.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
