{% set version = "2.3.0" %}
{% set sha256 = "231b7fced2485fa0945e01e4dd11fbb92d4aef74376a5ebe6e7c400dcc4e3c25" %}

package:
  name: pythreejs
  version: {{ version }}

source:
  fn: pythreejs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pythreejs/pythreejs-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - nodejs
  run:
    - python
    - ipywidgets >=7,<8
    - numpy
    - traittypes
    - ipydatawidgets

test:
  imports:
    - pythreejs

about:
  home: https://github.com/jupyter-widgets/pythreejs
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A Python / ThreeJS bridge utilizing the Jupyter widget infrastructure.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - vidartf
