{% set version = "0.3.0" %}
{% set sha256 = "e75b3a060d3b52732f9da2c0ecadb836219f54ed0f7bd54d5a5c2e123bee81f1" %}

package:
    name: pythreejs
    version: {{ version }}

source:
    fn: pythreejs-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/p/pythreejs/pythreejs-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - jupyter
    run:
        - python
        - ipywidgets >=6,<7

test:
    imports:
        - pythreejs

about:
    home: https://github.com/jovyan/pythreejs
    license: BSD 3-Clause
    summary: A Python / ThreeJS bridge utilizing the Jupyter widget infrastructure.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
