travis:
  secure:
    BINSTAR_TOKEN: GnlKJyAkvtAgxKzNve6qMpq4t68GdGNyzZlgzVOZMIIcQozNQ7NA27vJpgHmmqxn7qaf1PZHFMQiVecclj88u9Z9eGTZ2h3dJsigyb2cgGPL3XyJp7+bqV0WtO9W7ODPCHpxY7NoJaRapEtvP9anfcTxrBNlWVw44rx8TsQDe3Ew5nvgdcF+S7yI5oz9859QfaLwboBZ+fM2GjSagKLsvDVjRhSScoORZlfRAQV+YoaRDvQhVL5XcbzUw0tjCQstJUpwh4oUJ9Bv4kRy+4yjlC7QCMvOSKn+88NqNhZbwoftjKODjdipGKlJo0pUJRM/+WKY+fthpn1PHh4TbtWzuuX6vEzl66EKsWLD1hTyIKng8njFWay1Z8ZsyMelRBmi+8w1+KBbTHLDLiCpYVKsRxLsYs2fSpA5y116VSqRvZIw1tSigy1cZudKO49eOo1FOP6Cjvs7S3EnOFyiUS+5ZZihHPdxki+Efrbo+mo1rqtYDMN5NZgDPtpoaHC1fzwwX0Jst2M8DW/8/ttBXXwJhTbYdzmKQlLPLcJGcac/EKOM2kHzuET4PdhHjlEtnGadhl5nF6nN+fVmwTbonQYe3VA/wbdo+/Sc9oU12gNRR5kbs86mkexYo67si2kCROihfmXsb8Y4pV7cPCYqqioTSfQda7poehfvYjeodHfKPgA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
