appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: X8dtrcCHSFI5sGsbv41BUPoIKGVOBJ5l9bG8rJOvK+q5t7ApVGAbScbe0b4iKg5XyDzYsgT5cUaAxUWE6M4Hn0h9HJv8HEOTsZASNpY49pAK12PqzZ1LQVmmIm9A5UZx0cwFGUQ/FogSldYlcy5LcAjixZgTdN0wTHPbiVPQR+RNuFVOsTQpv2Pq3uA4Datau8OqTOtrq19deK2E3jOfE2qDwCSaFNyOtw3AdYnEQQIHU5Y+hi3Dk9zcz/GIvIfccnqID+pnvb5ACc15+FokxmYWv1FZDVlnHEZGkdD/VfzSYfRkE7F8EOhEDKru0zxXeq8zJUB3PhFAc4pG8Duc/sO9gfhZpv+TNAka2qOHAo5RGtmlzzZ1ei8MTFC+M2mwnwsHcZeQX9WxH7qWufE+SjTsv6iZj1/gRY2hdWeiJmJjNWllbh3iGmxCsb99U3lMCMbfotET+TpliLEDQX6MWPVdtXsCktQMQbjAgm1jCPAo9QWUGIrqLhIxp7Fc24c8GPak2/s9E7QyUG0KCPLmOSAo9OXS81nAw/Y/+AeDBtflSgPk3C1Nq7wPwFGVFuPsTVShKWGex2vniL71I4US7/RBJE8GK8LH6oo6TAOrd1WhESH0oj5De+JP8Qy61DUKvFPv2xCy9dS92rLc7Mn0fq4EXwwIeaut/h4rbGL5tBc=}
